name: Notion to Discord Notification

on:
  schedule:
    - cron: '0 23 * * *'  # 매일 오전 8시에 실행
  workflow_dispatch:  # 수동 실행을 허용

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run notification script
      env:
        NOTION_API_KEY: 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
        NOTION_DATABASE_ID: 1fa6ac36f09180e28b0de7f3b500534c
        DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1374711262436524052/VwtliynQZuU0uctmUdUIpw2TxeAzmQ3sduZX_gtUwX2nIf4nkAt4LisPXBxW6AZT90EN
      run: |
        python script.py
